// Seed product data with unique IDs and consistent image paths
const products = [
  { id: 1, 
   name: "Nike SB Dunk Orange Grateful Dead", 
   price: 86.00, 
   size: 10,
   image: "Nike SB Dunk Orange Grateful Dead (1).png", 
   page: "product1.html" },
  { id: 2, 
   name: "Nike x CRTZ", 
   price: 98.00,
   size: "10",
   image: "Nike x CRTZ  (1).png", 
   page: "product2.html" },
  { id: 3, 
   name: "Nike Hoodie", 
   price: 25.00,
   size: XXL,
   image: "Nike Hoodie (1).png", 
   page: "product3.html" },
  { id: 4, 
   name: "Balenciaga Track Pants", 
   price: 96.00,
   size: L,
   image: "Balenciaga Track Pants (2).png", 
   page: "product4.html" },
  { id: 5, 
   name: "Nike Air Max 95", 
   price: 76.00,
   size: 10,
   image: "Nike Air Max 95 OG Mandarin-2 (5).png", 
   page: "product5.html" },
  { id: 6, 
   name: "Nike X PSG Tech Fleece Zip-Up", 
   price: 30.00,
   size: M,
   image: "Nike X PSG Tech Fleece Zip-Up (4).png", 
   page: "product6.html" },
  { id: 7, 
   name: "Nike Sweatpants", 
   price: 20.00,
   size: M,
   image: "Nike Sweatpants (3).png", 
   page: "product7.html" },
  { id: 8, 
   name: "Nike Shox TL", 
   price: 50.00,
   size: 10,
   image: "Nike Shox TL Orange-Black (5).png", 
   page: "product8.html" },
];

localStorage.setItem("products", JSON.stringify(products));
